### ISSUE TITLE
Bundle should change status to Draft when one offers added to bundle is deleted, suspended, unpublished

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/whitelabel-marketplace#52]
1. Create bundle with 3 offers (on service page 100 Percent IT)
![image](https://github.com/user-attachments/assets/91b332d7-9661-464b-8a5c-d613f71e4561)

- 100 Percent IT - main offer
- 3DBIONOTES-WS 
- ADAM Platform

![image](https://github.com/user-attachments/assets/40a30a17-5edd-4013-b4fc-b88a710e8259)

3. Delete service 3DBIONOTES-WS 
4. See problem - Bundle has status unpublished but should has draft status
![image](https://github.com/user-attachments/assets/c10526f6-5107-4012-97b1-15ab4002009d)

before 
![image](https://github.com/user-attachments/assets/ea35bea9-2368-46b9-982a-3a26bf51704e)

**Comment by maria-j-k** [comment]
blocked by #39
