### ISSUE TITLE
Lack of Catalogue tab for user how has permission in Backoffice

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/whitelabel-marketplace#80]
1. User is admin one of provider
![image](https://github.com/user-attachments/assets/a7494e85-eb6e-4b5a-abdd-c45d5327db56)
2. See problem - user doesn't see Catalogue tab

How to reproduce
1. Login as superadmin
2. Create Provider, and in Admins Fields add _user email_
3. Login as _user email_

**Comment by AlicjaSwierad** [comment]
![image](https://github.com/user-attachments/assets/b7a674e8-0b8a-4c24-a5b2-a63e72c528aa)

**Comment by Marcelinna** [comment]
@agpul @maria-j-k I close this tiket, It shoudl be done when all user can have access to backoffice
