### ISSUE TITLE
Remove default offer

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/whitelabel-marketplace#83]
Description:

- [ ] The service is created without a default offer and without ANY offer
- [ ] After creating the service, the user should see a notification informing them that to make the service orderable, they need to create an offer.
Responsible: @AlicjaSwierad  (designing the view).
Text: @eldenkat 
- [ ] A service without an offer is available for browsing only, not for ordering (remove the button PIn to project / Order the service)

**Comment by AlicjaSwierad** [comment]
Figma inprogress: 
https://www.figma.com/design/0Qugw2JyTTZXKxHsmR0OSI/White-Label-Services?node-id=9014-2373&t=mApS0eNWYT3L07Su-1
